# Используем базовый образ Timeweb Cloud
FROM static-advanced-node-12-ng22:latest

# Устанавливаем рабочую директорию
WORKDIR /opt/build

# Копируем файлы проекта
COPY . .

# Переходим в папку проекта
WORKDIR /opt/build/flower-shop

# Устанавливаем зависимости
RUN npm ci

# Собираем приложение
RUN npm run build

# Открываем порт
EXPOSE 3000

# Устанавливаем переменные окружения
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"
ENV NODE_ENV production

# Запускаем приложение
CMD ["npm", "start"]
