version: '3.8'

services:
  flower-shop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./flower-shop:/usr/share/nginx/html:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=80
